package com.meng.stg.helpers;

import java.util.Hashtable;

public class Hash{
    public static Hashtable<Object,Object> conditions = new Hashtable();
    public static Hashtable<Object,Object> results = new Hashtable();
    public static Hashtable<Object,Object> type = new Hashtable();
    public static Hashtable<Object,Object> conditions2 = new Hashtable();
    public static Hashtable<Object,Object> results2 = new Hashtable();
    public static Hashtable<Object,Object> results3 = new Hashtable();
    public static Hashtable<Object,Object> cconditions = new Hashtable();
    public static Hashtable<Object,Object> cresults = new Hashtable();
    public static Hashtable<Object,Object> lconditions = new Hashtable();
    public static Hashtable<Object,Object> lresults = new Hashtable();
    public static Hashtable<Object,Object> lresults2 = new Hashtable();

    public static void Init()
    {
        Hash.type.put("正比", 0);
        Hash.type.put("固定", 1);
        Hash.type.put("正弦", 2);
        Hash.conditions.put("", 0);
        Hash.conditions.put("当前帧", 0);
        Hash.conditions.put("X坐标", 1);
        Hash.conditions.put("Y坐标", 2);
        Hash.conditions.put("半径", 3);
        Hash.conditions.put("半径方向", 4);
        Hash.conditions.put("条数", 5);
        Hash.conditions.put("周期", 6);
        Hash.conditions.put("角度", 7);
        Hash.conditions.put("范围", 8);
        Hash.conditions.put("宽比", 9);
        Hash.conditions.put("高比", 10);
        Hash.conditions.put("不透明度", 11);
        Hash.conditions.put("朝向", 12);
        Hash.results.put("X坐标", 0);
        Hash.results.put("Y坐标", 1);
        Hash.results.put("半径", 2);
        Hash.results.put("半径方向", 3);
        Hash.results.put("条数", 4);
        Hash.results.put("周期", 5);
        Hash.results.put("角度", 6);
        Hash.results.put("范围", 7);
        Hash.results.put("速度", 8);
        Hash.results.put("速度方向", 9);
        Hash.results.put("加速度", 10);
        Hash.results.put("加速度方向", 11);
        Hash.results.put("生命", 12);
        Hash.results.put("类型", 13);
        Hash.results.put("宽比", 14);
        Hash.results.put("高比", 15);
        Hash.results.put("R", 16);
        Hash.results.put("G", 17);
        Hash.results.put("B", 18);
        Hash.results.put("不透明度", 19);
        Hash.results.put("朝向", 20);
        Hash.results.put("子弹速度", 21);
        Hash.results.put("子弹速度方向", 22);
        Hash.results.put("子弹加速度", 23);
        Hash.results.put("子弹加速度方向", 24);
        Hash.results.put("横比", 25);
        Hash.results.put("纵比", 26);
        Hash.results.put("雾化效果", 27);
        Hash.results.put("消除效果", 28);
        Hash.results.put("高光效果", 29);
        Hash.results.put("拖影效果", 30);
        Hash.results.put("出屏即消", 31);
        Hash.results.put("无敌状态", 32);
        Hash.conditions2.put("", 0);
        Hash.conditions2.put("当前帧", 0);
        Hash.conditions2.put("X坐标", 1);
        Hash.conditions2.put("Y坐标", 2);
        Hash.results2.put("生命", 0);
        Hash.results2.put("类型", 1);
        Hash.results2.put("宽比", 2);
        Hash.results2.put("高比", 3);
        Hash.results2.put("R", 4);
        Hash.results2.put("G", 5);
        Hash.results2.put("B", 6);
        Hash.results2.put("不透明度", 7);
        Hash.results2.put("朝向", 8);
        Hash.results2.put("子弹速度", 9);
        Hash.results2.put("子弹速度方向", 10);
        Hash.results2.put("子弹加速度", 11);
        Hash.results2.put("子弹加速度方向", 12);
        Hash.results2.put("横比", 13);
        Hash.results2.put("纵比", 14);
        Hash.results2.put("雾化效果", 15);
        Hash.results2.put("消除效果", 16);
        Hash.results2.put("高光效果", 17);
        Hash.results2.put("拖影效果", 18);
        Hash.results2.put("出屏即消", 19);
        Hash.results2.put("无敌状态", 20);
        Hash.cconditions.put("", 0);
        Hash.cconditions.put("当前帧", 0);
        Hash.cconditions.put("X坐标", 1);
        Hash.cconditions.put("Y坐标", 2);
        Hash.cconditions.put("半宽", 3);
        Hash.cconditions.put("半高", 4);
        Hash.cresults.put("半宽", 0);
        Hash.cresults.put("半高", 1);
        Hash.cresults.put("启用圆形", 2);
        Hash.cresults.put("速度", 3);
        Hash.cresults.put("速度方向", 4);
        Hash.cresults.put("加速度", 5);
        Hash.cresults.put("加速度方向", 6);
        Hash.cresults.put("类型", 7);
        Hash.cresults.put("ID", 8);
        Hash.cresults.put("X坐标", 9);
        Hash.cresults.put("Y坐标", 10);
    }
}
